---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-httpd
  labels:
    app: sample-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-httpd
  template:
    metadata:
      labels:
        app: sample-httpd
    spec:
      containers:
      - name: sample-httpd
        image: httpd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: httpd-conf
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf
      volumes:
      - name: httpd-conf
        configMap:
          name: httpd-conf
          items:
          - key: httpd.conf
            path: httpd.conf
